### ISSUE TITLE
Insufficient Privileges

### ISSUE THREAD

**Issue by JAK1047** [MarcelMeurer/Project-MySmartScale#1]
Didn't know if there was a forum or better place to reach out for assistance, but after following the instructions and setting up the portal I'm getting an HTTP 500 error every few seconds in it while it tries to pull Data\Statistics. Looking at the response it appears to be getting an ODATA Insufficient Privileges error.

I'm assuming the error is from the Service Principal set up in the Portal App Configuration missing some rights, but it's set for User.Read.All under Application and ID Token is checked. I haven't setup the agent yet on my WVD hosts wanting to get the basic setup out of the way, so any idea what the periodic calls trying to access that could be generating the error? Or where I could start troubleshooting?

**Comment by MarcelMeurer** [comment]
Hi. This is the absolute right place. So, thanks for placing your question here.

Can you log in properly to the -portal web site and do you see the web GUI without tiles (empty)? This should be. If you can log in, the portal queries the data once in a minute. The data Uri is:

https://nnnnnnnnnnnnn-portal.azurewebsites.net/data/SiteStatistics/1AF04A50-3F2F-420A-93B8-2D2A1EFF6CF1

The return value for a vanilla installation is: [] - 200

If you get an error there is something wrong. Maybe, you wrote, with your authentication. Could you check the configuration variables:

```
ida:ClientId: <Id of your Azure Ad app / service principal Guid>
ida:ClientSecret: <Secret of your Azure Ad app / service principal>
ida:Domain: <Your Azure AD tenant Guid>
ida:TenantId: <Your Azure AD tenant Guid>
```

Also, make sure that you leave this variable as it is/was. It must be the static Guid:
`cfg:DefaultTenantGuid: 1AF04A50-3F2F-420A-93B8-2D2A1EFF6CF1`

Another thing: Make sure that you open the **-portal** URI and not the -data once. The -data has no website and will give you an error if access them. -data holds the web job and data endpoint. You can check if the endpoint is working with https://nnnnnnnnnnnnn-portal.azurewebsites.net/data/test

**Comment by JAK1047** [comment]
![image](https://user-images.githubusercontent.com/29665481/67112174-9ea42980-f1a4-11e9-97df-188bd0dca03f.png)

Rebuilt from scratch just to see and got the same thing. Portal loads, but errors persist every full seconds. Made sure the configuration is in the Portal app and not data. Values appear right (Haven't set the AdminUserGroup yet on this new one). I took a screenshot and removed the ending characters,

![image](https://user-images.githubusercontent.com/29665481/67112431-3a359a00-f1a5-11e9-9a91-45825dde5105.png)

![image](https://user-images.githubusercontent.com/29665481/67112546-7bc64500-f1a5-11e9-80a7-a1f50000f101.png)

![image](https://user-images.githubusercontent.com/29665481/67112585-913b6f00-f1a5-11e9-94e4-834a93140e4a.png)

![image](https://user-images.githubusercontent.com/29665481/67112620-a912f300-f1a5-11e9-8467-054293c3568a.png)

![image](https://user-images.githubusercontent.com/29665481/67112679-c942b200-f1a5-11e9-9f99-81327a757759.png)

As far as I can tell it is set correctly, but I don't know what calls are being made from that error.

**Comment by MarcelMeurer** [comment]
Hi. Did you get the Azure log on screen if you open the portal? The next step would be to check the application insight log. Maybe there is an error connecting to the database. You can check the connection string of the portal web app. Maybe you have some special character which not worked (like a "). Or, if it an option, give me temporary permissions to the resource group to support debugging.

**Comment by JAK1047** [comment]
No login page just took me right in. I'll take a look when Monday rolls around and I'm back at work to see if the logs have anything further and let you know. Thank you!

**Comment by JAK1047** [comment]
Might be a moot point anyway. Now when I try to do another deployment I'm getting failures in the ARM template.

![image](https://user-images.githubusercontent.com/29665481/67237919-32326000-f41a-11e9-9138-9b6c84158c42.png)

"ErrorEntity": { "ExtendedCode": "51004", "MessageTemplate": "Cannot find {0} with name {1}.", "Parameters": [ "ServerFarm", "WindScaleTest" ], "Code": "NotFound", "Message": "Cannot find ServerFarm with name WindScaleTest." }

So it successfully made the ServerFarm right below it, then failed to find the ServerFarm it just created.

**Comment by MarcelMeurer** [comment]
Hi. I’m sorry about the trouble you have rolling out the solution. I tried this right now and if I choose a deployment name which is probably random (like projectmysmartscale20191022) it is deployed without problems. To choose the right name is with this git hub repo a challenge: you are free to select a name but it must fit and be unique for the resources like web app, SQL, log analytics, …
But I see in your screenshot that your name is probably unique. Your error message looks like the server farm (app service plan) might not be ready while rolling out the data web app. I checked the dependencies of the web app with the server farm and this is right.

Could you repeat rolling out the solution? Maybe there was a random issue in the deployment phase.

Sorry about the issues you have. This is not that was I want to have.
Marcel

Here a screenshot of my current deployment:
[cid:image001.jpg@01D58875.5D9AB9B0]

**Comment by JAK1047** [comment]
Tried a different browser, account, and a name with random numbers, so I'm _assuming_ that it's unique. Same issue:

![image](https://user-images.githubusercontent.com/29665481/67302063-534c8c80-f4be-11e9-82c2-d127c639ca9c.png)

Is the data site something I could manually create myself?

**Comment by MarcelMeurer** [comment]
Can you tun the deployment with the same name and pssword in the same rg? Alternatively, you can build the web app by yourself but you have to add the settings and configurations by yourself (are your able to read this from the arm template?). Could you name me the region you have used?

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by MarcelMeurer** [comment]
Sorry. If found the error. There was a hardcoded location in the arm template. I corrected it now. Sorry again and I hope it works now like expected.

**Comment by JAK1047** [comment]
Looks like that fixed it! I'll go through when it finishes and set it up to get back on track with the original issue, but wanted to let you know that error is corrected for tracking.

**Comment by JAK1047** [comment]
Think I see the issue in the App Insights. Does that https://nnnnnnnnnnnnn-portal.azurewebsites.net/data/SiteStatistics/1AF04A50-3F2F-420A-93B8-2D2A1EFF6CF1

Do a SQL query? Because I see errors trying:

Remote dependency name | SQL: tcp:WindScale3.database.windows.net,1433 \| MySmartScale

And we are on an ExpressRoute vNET behind an on premise firewall. Older Cisco ASA 5555 firewalls that don't allow URL wildcarding, so I'll probably have to have the database it opens allowed through the ACE. I'll reach out to our network team and try that if that makes sense to you.

**Comment by JAK1047** [comment]
So after my last thought on the Azure Active Directory Graph I threw on those perms:

![image](https://user-images.githubusercontent.com/29665481/67513552-0a850700-f669-11e9-86b3-abf5d153f615.png)

After 10 minutes the calls started working. I can remove the perms one, by one to test the exact, but this is looking good to me.
