### ISSUE TITLE
Error, any idea ?

### ISSUE THREAD

**Issue by Go0ners** [MarcelMeurer/Project-MySmartScale#3]
> [ArgumentException: Format of the initialization string does not conform to specification starting at index 133.]
>    System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue) +1984
>    System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey) +196
>    System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules) +135
>    System.Data.SqlClient.SqlConnectionString..ctor(String connectionString) +71
>    System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous) +35
>    System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions) +214
>    System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key) +75
>    System.Data.SqlClient.SqlConnection.set_ConnectionString(String value) +116
>    System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) +104
>    System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.SetConnectionString(DbConnection connection, DbConnectionPropertyInterceptionContext`1 interceptionContext) +503
>    System.Data.Entity.Internal.LazyInternalConnection.TryInitializeFromAppConfig(String name, AppConfig config) +39
>    System.Data.Entity.Internal.LazyInternalConnection.Initialize() +161
>    System.Data.Entity.Internal.LazyInternalConnection.get_ProviderName() +16
>    System.Data.Entity.Internal.DefaultModelCacheKeyFactory.Create(DbContext context) +132
>    System.Data.Entity.Internal.LazyInternalContext.InitializeContext() +716
>    System.Data.Entity.Internal.LazyInternalContext.MarkDatabaseInitialized() +22
>    Administration.MvcApplication.Application_Start() +234
> 
> [HttpException (0x80004005): Format of the initialization string does not conform to specification starting at index 133.]
>    System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +520
>    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +176
>    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +165
>    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +267
>    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +341
> 
> [HttpException (0x80004005): Format of the initialization string does not conform to specification starting at index 133.]
>    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +523
>    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +107
>    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +688`
![image](https://user-images.githubusercontent.com/9991683/76516314-7a026400-645b-11ea-9528-8c64623afe02.png)

If you have an idea? I followed the README...
Thanks

**Comment by MarcelMeurer** [comment]
I guess that you try to open the -portal.azurewebsites.net, correct?

Could you check the web app for the -portal: Configuration -> Connection Strings

There are two connection strings: ScContext and DbContext 

They should look like that:

Server=tcp:<databasename>.database.windows.net,1433;Initial Catalog=MySmartScale;Persist Security Info=False;User ID=dbadmin;Password=<yourPasswordForTheSqlDb>;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=90;

Check your password. Maybe the password contains some invalid characters like ;
