### ISSUE TITLE
Site Collection name

### ISSUE THREAD

**Issue by xarly** [MarcelMeurer/Project-MySmartScale#5]
Hello,

Im testing this with WVD and 5 hosts, I have set up EndPoint keys in config, but in panel the site collection is named Staging, not actual name of HostPool-SiteCollection like your screenshot..

Config is set like this, is not ok?
```
    <add key="SiteCollection" value="Staging"/> <!-- is used for RDS if "SiteCollection-RdsUseSessionDirectoryClusterName" not "1"-->
    <add key="SiteCollection-RdsUseSessionDirectoryClusterName" value="1"/>   <!-- For WVD set it to: "1"-->
    <add key="TimeOutSessionDisconnectedHandleAsLogoff" value="360"/>
```

Thanks

**Comment by MarcelMeurer** [comment]
Hi Xarly.

This is correct. There is a known issue with the WVD agent from Microsoft. The agent writes the tenant name and host pool in the registry. This is used by my agent. Unfortunately, the RD agent doesn't write this if you have a language pack installed on the session host.

I wrote a blog post about this behavior and I have a workaround for MySmartScale and Azure Monitor for WVD. The easiest way is to use #WVDAdmin to work with your environment and roll out new session hosts. WVDAdmin sets tags on the session host which are used by my solutions to get the name of the tenant and host pool (WVD.Path=Tenant\TenantGroup\HostPool).

Does this work for you?

**Comment by xarly** [comment]
Thanks for quick reply, The thing is that I use Shared Image Gallery for versioning my session hosts, and I deploy new hosts with latest version in SIG, but WVDAdmin (great tool!) does not support SIG yet, as I see

**Comment by xarly** [comment]
I have seen the workaround with tags in VM, I can do that :) Thanks! 

By the way, do you plan to include SIG support in WVDAdmin? :)

**Comment by MarcelMeurer** [comment]
Let me check this. How do you use SIG today? I guess that you have prepared images with your apps in SIG. Have you captured this image from a template VM?

**Comment by xarly** [comment]
I created a VM with Win10 Multissesión from Azure Marketplace and installed my LOB applications, then I syspreped, captured and added as a versión 1.0.0 to SIG.

After that if I need to update or whatever I deploy from SIG latest versión, sysprep, capture and add as new versión.

For deployment I remove all sessión hosts, and create new deployment using ARM templates from https://roeleverink.nl/SIG-and-WVD/#deploy-wvd-from-sig referecing my Image Definitions, using latest version available

**Comment by MarcelMeurer** [comment]
I can build that admins can use images from SIG to deploy VMs. I put this on my list. Thanks for your explanation.
