### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by MiguelJamous** [MarcelMeurer/Project-MySmartScale#7]
Hi Marcel,
Great Job, love your WVDAdmin en Hydra.
How can you re-order the pools in the dashboard?
Thanks,
Miguel

**Comment by MarcelMeurer** [comment]
Hi MiguelJamous. In "Project-MySmartScale" or in hydra? Right now the tiles in this project are sorted by user sessions. In Hydra, the host pools are sorted by name. What do you think is the best way to sort the host pools? Thanks a lot for the feedback.

**Comment by MiguelJamous** [comment]
Hi Marcel,
in Hydra, that the pools are sorted by name is perfect, but the layout is by me on top on each other, when there is place on the right, in your youtube video at 8.33 i see 3 on each row, how do you arrange that
![hydra](https://user-images.githubusercontent.com/49722870/123395687-c619df00-d5a0-11eb-89fa-19a0d658611c.JPG)

**Comment by MiguelJamous** [comment]
Sorry, i just notice i am in the wrong project, i will post this in hydra

**Comment by MarcelMeurer** [comment]
Move to the WVD-Hydra repo
